const verbo1 = "Tengo";
const verbo2 = "Quiero";
const frase = "ganas de comer";
const animal = "perros";
const temperatura1 = "calor";
const temperatura2 = "frío";
const comida1 = "sandía";
const comida2 = "paella";

let resultado = verbo1+" "+animal;
console.log(resultado);
resultado = verbo1+" "+temperatura1;
console.log(resultado);
resultado = verbo1+" "+temperatura2;
console.log(resultado);
resultado = verbo1+" "+frase+" "+comida1;
console.log(resultado);
resultado = verbo1+" "+frase+" "+comida2;
console.log(resultado);
resultado = verbo2+" "+temperatura2;
console.log(resultado);
resultado =verbo2+" "+temperatura1;
console.log(resultado);
resultado =verbo2+" "+comida1;
console.log(resultado);
resultado = verbo2+" "+comida2;
console.log(resultado);
resultado =verbo2+" "+animal;
console.log(resultado);